name: Build and deploy website

on:
  push:
    branches:
    - 'master'
  schedule:
    # Every six hours update the web site
    - cron:  '0 */6 * * *'
  pull_request:
    branches:
      - 'master'
      - 'v0.1.0'
    paths-ignore:
    - 'static/install.sh'

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.2'
          extended: true

      - name: Install jq
        uses: r26d/jq-action@master

      - name: Fetch dynamic content
        run: scripts/fetch_dynamic_content.sh

      - name: Build
        run: npm install && hugo --minify

      - name: Store build artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@master
        with:
          name: website
          path: ./public 

  Deploy:
    name: Deploy to GitHub Pages
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch build artifacts
        uses: actions/download-artifact@master
        with:
          name: website
          path: ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
