name: Build website and deploy to GitHub Pages

on:
  push:
    branches:
    - 'master'
  schedule:
    # Every six hours update the web site
    - cron:  '0 */6 * * *'
  pull_request:
    branches:
      - 'master'
      - 'v0.1.0'
    paths-ignore:
    - 'static/install.sh'

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.2'
          extended: true

      - name: Install jq
        uses: r26d/jq-action@master

      - name: Fetch Core Contributors
        run: "curl https://api.github.com/repos/owncast/owncast/contributors?per_page=100 | jq 'map(.) | .[] | {login: .login, avatar_url: .avatar_url, html_url: .html_url}' | jq --slurp '.' > data/contributors-core.json"

      - name: Fetch Admin Contributors
        run: "curl https://api.github.com/repos/owncast/owncast-admin/contributors?per_page=100 | jq 'map(.) | .[] | {login: .login, avatar_url: .avatar_url, html_url: .html_url}' | jq --slurp '.' > data/contributors-admin.json"

      - name: Fetch Home Page Contributors
        run: "curl https://api.github.com/repos/owncast/owncast.github.io/contributors?per_page=100 | jq 'map(.) | .[] | {login: .login, avatar_url: .avatar_url, html_url: .html_url}' | jq --slurp '.' > data/contributors-homepage.json"

      - name: Combine Contributors
        run: "jq --argfile core data/contributors-core.json --argfile admin data/contributors-admin.json --argfile homepage data/contributors-homepage.json -n '$core + $admin + $homepage |unique_by(.login)' > data/contributors.json"
      
      - name: Fetch donors
        run: "curl https://opencollective.com/owncast/members/all.json | jq 'map(.) | .[] | select(.role==\"BACKER\") | {login: .name, avatar_url: .image, html_url: .profile}' | jq --slurp '.' > data/donors.json"

      - name: Add current development documentation
        run: mkdir -p static/api/development && curl https://raw.githubusercontent.com/owncast/owncast/master/doc/api/index.html > static/api/development/index.html

      - name: Update dynamic content
        if: github.event_name != 'pull_request'
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Owncast
          author_email: owncast@owncast.online
          message: "Update dynamic content"
          add: "static/api/development/index.html data/contributors.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: npm install && hugo --minify

      - name: Upload artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@master
        with:
          name: website
          path: ./public 

  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: website
          path: ./public

      - name: Deploy on GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
