name: Lint

on:
  push:
    branches:
      - 'master'
    paths:
      - '**.sh'
  pull_request:
    branches:
      - 'master'
      - 'v0.1.0'
    paths:
      - '**.sh'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8
    container:
      image: docker.io/ubuntu:22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install shellcheck
        run: apt update && apt install -y shellcheck bash && shellcheck --version

      - name: Check shell scripts
        run: shopt -s globstar && ls **/*.sh && shellcheck --severity=info **/*.sh
        shell: bash
